// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";

export let options = {
  maxRedirects: 4,
  duration: "1m",
  vus: 100
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "graph1",
    id: "0a5b88fb-7a8f-4568-9b9e-798ad83fed90",
    method: "GET",
    address: "http://127.0.0.1:5000/plots/0"
  });

  postman[Request]({
    name: "graph2",
    id: "958de57c-53bb-433f-a971-6d061712b0d7",
    method: "GET",
    address: "http://127.0.0.1:5000/plots/1"
  });

  postman[Request]({
    name: "graph3",
    id: "fc10eced-d54d-48a5-8aad-656f81a211d7",
    method: "GET",
    address: "http://127.0.0.1:5000/plots/3"
  });

  postman[Request]({
    name: "graph4",
    id: "ebd95f21-1096-420e-a845-afaf4294082a",
    method: "GET",
    address: "http://127.0.0.1:5000/plots/2"
  });

  postman[Request]({
    name: "graph5",
    id: "d414d853-1ff7-4b08-b29f-6965856bc866",
    method: "GET",
    address: "http://127.0.0.1:5000/plots/5"
  });
}
