// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";

export let options = {
  maxRedirects: 4,
  duration: "1m",
  vus: 100
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "addData",
    id: "e12ee4dd-901b-4581-a533-78472bbfc324",
    method: "POST",
    address: "http://127.0.0.1:5000/addData",
    data:
      '{"id":"169967", "gender": "Male", "age": "21", "hypertension": "False", "heart_disease": "True", "ever_married": "True", "work_type": "Private", "Residence_type": "Urban", "avg_glucose_level": "123", "bmi": "345", "smoking_status": "never_smoked", "stroke":"False"}',
    headers: {
      "Content-Type": "application/json"
    }
  });

  postman[Request]({
    name: "getEntry",
    id: "3d29fb09-ae3d-4c74-be0f-e7e604c0f650",
    method: "POST",
    address: "http://127.0.0.1:5000/getEntry/<id>",
    data: '{"id":"1278"}',
    headers: {
      "Content-Type": "application/json"
    }
  });

  postman[Request]({
    name: "delEntry",
    id: "fb97b2f2-411b-4029-bb47-f731e518fdae",
    method: "DELETE",
    address: "http://127.0.0.1:5000/delEntry/234",
    headers: {
      "Content-Type": "application/json"
    }
  });

  postman[Request]({
    name: "predict",
    id: "6e20787a-4aab-4bfd-84b0-2a7cacc1c25e",
    method: "POST",
    address: "http://127.0.0.1:5000/predict",
    data:
      '{"id":"24", "gender": "Male", "age": "21", "hypertension": "False", "heart_disease": "True", "ever_married": "True", "work_type": "Private", "Residence_type": "Urban", "avg_glucose_level": "123", "bmi": "345", "smoking_status": "never_smoked"}',
    headers: {
      "Content-Type": "application/json"
    }
  });

  postman[Request]({
    name: "metrics",
    id: "c49d9f3e-59e1-4306-80e1-c63b566714c7",
    method: "GET",
    address: "http://127.0.0.1:5000/metrics"
  });

  postman[Request]({
    name: "correlation",
    id: "7d25a4c7-5093-4e39-83c3-4f297fe4cd9e",
    method: "GET",
    address: "http://127.0.0.1:5000/correlation"
  });

  postman[Request]({
    name: "confusion",
    id: "2dde1c20-9b1d-4c2c-bd33-4191c606db81",
    method: "GET",
    address: "http://127.0.0.1:5000/confusion"
  });

  postman[Request]({
    name: "graph1",
    id: "86b95243-f90f-4c71-b94e-a9712efc6e44",
    method: "GET",
    address: "http://127.0.0.1:5000/plots/0"
  });
}
