// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";

export let options = {
  maxRedirects: 4,
  duration: "1m",
  vus: 100
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "graph1",
    id: "59742132-dd26-45ec-a5ce-395da4213ee6",
    method: "GET",
    address: "http://127.0.0.1:5000/plots/4"
  });

  postman[Request]({
    name: "graph2",
    id: "8962f6b4-312c-4ace-b7c3-e15a938ee954",
    method: "GET",
    address: "http://127.0.0.1:5000/plots/6"
  });

  postman[Request]({
    name: "graph3",
    id: "9e478b97-1131-48fb-9f55-42781ae8fde8",
    method: "GET",
    address: "http://127.0.0.1:5000/plots/0"
  });

  postman[Request]({
    name: "graph4",
    id: "6dda1917-55a9-4118-8eaa-e0ec92409cd7",
    method: "GET",
    address: "http://127.0.0.1:5000/plots/0"
  });

  postman[Request]({
    name: "graph5",
    id: "fc9ff4e2-f46a-435c-bcf0-776ba70fbfa6",
    method: "GET",
    address: "http://127.0.0.1:5000/plots/3"
  });
}
