// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";

export let options = {
  maxRedirects: 4,
  duration: "1m",
  vus: 100
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "getEntry1",
    id: "bf734802-ef49-4d5d-8ea8-4279c40a5951",
    method: "POST",
    address: "http://127.0.0.1:5000/getEntry/<id>",
    data: '{"id":"1"}',
    headers: {
      "Content-Type": "application/json"
    }
  });

  postman[Request]({
    name: "Delete1",
    id: "489fce5e-8cb3-40a4-8912-5eae57679bcb",
    method: "DELETE",
    address: "http://127.0.0.1:5000/delEntry/1",
    headers: {
      "Content-Type": "application/json"
    }
  });

  postman[Request]({
    name: "getEntry2",
    id: "5f2d528a-1d83-4171-95b4-7ebe22967889",
    method: "POST",
    address: "http://127.0.0.1:5000/getEntry/<id>",
    data: '{"id":"123456789"}',
    headers: {
      "Content-Type": "application/json"
    }
  });

  postman[Request]({
    name: "getEntry3",
    id: "3b3ddc92-c846-41c1-a363-95dd873d60cc",
    method: "POST",
    address: "http://127.0.0.1:5000/getEntry/<id>",
    data: '{"id":"154"}',
    headers: {
      "Content-Type": "application/json"
    }
  });

  postman[Request]({
    name: "Delete2",
    id: "0eea4cb8-b866-4fe8-b88b-a42678936627",
    method: "DELETE",
    address: "http://127.0.0.1:5000/delEntry/1876543"
  });
}
