// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";

export let options = {
  maxRedirects: 4,
  duration: "1m",
  vus: 200
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "Predict",
    id: "b48b1df5-f8a9-4083-909b-049c316e9e78",
    method: "POST",
    address: "http://127.0.0.1:5000/predict",
    data:
      '{"id":"1", "gender": "Male", "age": "21", "hypertension": "False", "heart_disease": "True", "ever_married": "True", "work_type": "Private", "Residence_type": "Urban", "avg_glucose_level": "123", "bmi": "345", "smoking_status": "never_smoked"}',
    headers: {
      "Content-Type": "application/json"
    }
  });

  postman[Request]({
    name: "Metrics",
    id: "f3e6a7c0-93f9-44b8-9422-fa5728d9deaa",
    method: "GET",
    address: "http://127.0.0.1:5000/metrics"
  });

  postman[Request]({
    name: "Correlation",
    id: "68599773-af70-4998-a0ea-73fb1b9cad90",
    method: "GET",
    address: "http://127.0.0.1:5000/correlation"
  });

  postman[Request]({
    name: "Confusion",
    id: "c9925105-4194-420b-b56c-04a4346fe310",
    method: "GET",
    address: "http://127.0.0.1:5000/confusion"
  });
}
